
{{-- ======================================================================
     KOMPONEN: Calendar Dropdown
     Deskripsi: Komponen kalender interaktif untuk memilih tanggal.
                Terdiri dari header (bulan/tahun), grid tanggal, 
                dan tombol aksi di footer.
     ====================================================================== --}}
<div class="calendar-dropdown {{ $class ?? '' }}" id="{{ $id ?? 'calendar-dropdown' }}" data-target="{{ $target ?? '' }}">

    {{-- 1. BAGIAN HEADER: Label Bulan & Tombol Navigasi --}}
    <div class="calendar-header">
        
        {{-- Label Bulan dan Tahun (Diisi via JS) --}}
        <h3 class="month-year-label">...</h3>
        
        {{-- Tombol Navigasi Bulan --}}
        <div class="header-nav">
            
            {{-- Tombol Bulan Sebelumnya --}}
            <button type="button" class="nav-btn prev-month" title="Bulan Sebelumnya">
                <svg viewBox="0 0 22 22" fill="none">
                    <path d="M13.293 5.5L7.79297 11L13.293 16.5" stroke="#101828" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
            </button>
            
            {{-- Tombol Bulan Berikutnya --}}
            <button type="button" class="nav-btn next-month" title="Bulan Berikutnya">
                <svg viewBox="0 0 22 22" fill="none">
                    <path d="M8.70703 5.5L14.207 11L8.70703 16.5" stroke="#101828" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
            </button>

        </div>
    </div>

    {{-- 2. BAGIAN GRID: Nama Hari & Kotak Tanggal --}}
    <div class="calendar-grid">
        <div class="calendar-grid-wrapper">
            {{-- Header Nama Hari (Minggu - Sabtu) --}}
            <div class="day-names">
                <span>MG</span>
                <span>SN</span>
                <span>SL</span>
                <span>RB</span>
                <span>KM</span>
                <span>JM</span>
                <span>SB</span>
            </div>
            
            {{-- Container Tanggal (Elemen hari akan di-generate via JS) --}}
            <div class="date-grid calendar-days-container">
                {{-- Days will be generated by JS --}}
            </div>
        </div>
    </div>

    {{-- 3. BAGIAN FOOTER: Tombol Aksi Tambahan --}}
    <div class="calendar-footer">
        {{-- Tombol untuk membersihkan pilihan tanggal --}}
        <button type="button" class="footer-btn btn-clear">Bersihkan</button>
        
        {{-- Tombol untuk kembali ke tanggal hari ini --}}
        <button type="button" class="footer-btn btn-today">Hari ini</button>
    </div>

</div>